#
# Copyright (C) 2025-2026 luci-theme-echo contributors
# Licensed under the Apache License, Version 2.0
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Echo Theme Configuration
LUCI_DEPENDS:=+luci-theme-echo +luci-base
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

define Package/luci-app-echo-config/conffiles
/etc/config/echo
endef

# call BuildPackage - OpenWrt buildroot signature
